In [1]:
import numpy as np
sentence="Jefferson Monticello Thomas age at began building of the 26."





[[0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0]]


In [ ]:
#dzielimy na tokeny
token_sequence = str.split(sentence)
#usuwamy duplikaty i sortujemy
vocab = sorted(set(token_sequence))     

In [ ]:
num_tokens = len(token_sequence)
vocab_size = len(vocab)
#tworzymy macierz o wymiarach liczba_tokenow_w_sentencjixliczba_unikalnych_slow
onehot_vectors = np.zeros((num_tokens,vocab_size), int)

In [ ]:
for i, word in enumerate(token_sequence):
     onehot_vectors[i, vocab.index(word)] = 1

In [ ]:
print(onehot_vectors)